### ISSUE TITLE
界面细节优化

### ISSUE THREAD

**Issue by wangrunlin** [idea2app/idea2app.github.io#43]
## 说明

这个 issue 内可以提出在使用过程中 UI 的问题

## 待优化

- [ ] 导航栏文字添加[响应式断点 ](https://getbootstrap.com/docs/5.3/layout/breakpoints/)
![image](https://github.com/idea2app/idea2app.github.io/assets/64216877/ea26d46a-cd94-4ba9-a851-79e9d41aeab0)

**Comment by TechQuery** [comment]
- [ ] 取消项目价格显示
